### ISSUE TITLE
new-component command failed on every OS

### ISSUE THREAD

**Issue by duyisking** [rezo-labs/universal-react-app#14]
**Describe the bug**
Cannot run command new-component on every OS (Windows, Linux, OSX).

**To Reproduce**
1. Run command `npm run new-component`

**Expected behavior**
The command run as expected.

**Current behavior**
Failed with error:
```
/home/duyisking/Documents/Rezo-projects/universal-react-app/configs/scripts/new-component/validate.js:47
export {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/duyisking/Documents/Rezo-projects/universal-react-app/configs/scripts/new-component/index.js:18:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-react-app@1.4.1 new-component: `node configs/scripts/new-component`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the universal-react-app@1.4.1 new-component script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/duyisking/.npm/_logs/2019-06-19T13_10_20_920Z-debug.log
```

**Comment by duyisking** [comment]
Solved on #15
